gateway_name: sila2_lab_automation_gateway
gateway_description: "SiLA2 Lab Automation Gateway for AgentCore"
region: us-west-2
execution_role_arn: arn:aws:iam::590183741681:role/sila2-lab-automation-phase3-complete-lambda-execution-role

tools:
  - name: list_devices
    description: "List all available SiLA2 devices"
    handler: gateway.sila2_gateway_tools_phase3:list_available_devices
    parameters:
      type: object
      properties: {}
  
  - name: device_status
    description: "Get status of a specific device"
    handler: gateway.sila2_gateway_tools_phase3:get_device_status
    parameters:
      type: object
      properties:
        device_id:
          type: string
          description: "Device identifier"
      required: ["device_id"]
  
  - name: start_operation
    description: "Start operation on a device"
    handler: gateway.sila2_gateway_tools_phase3:start_device_operation
    parameters:
      type: object
      properties:
        device_id:
          type: string
          description: "Device identifier"
        operation:
          type: string
          description: "Operation to start"
      required: ["device_id", "operation"]

environment_variables:
  API_GATEWAY_URL: https://jn77k8pgyh.execute-api.us-west-2.amazonaws.com/dev
  ENVIRONMENT: dev
