default_agent: sila2_phase3_agent
agents:
  sila2_phase3_agent:
    name: sila2_phase3_agent
    entrypoint: main_agentcore_phase3.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::590183741681:role/sila2-phase3-architecture-compl-DeviceApiLambdaRole-CyYxEA1svxeL
      execution_role_auto_create: true
      account: '590183741681'
      region: us-west-2
      ecr_repository: 590183741681.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-sila2_phase3_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: sila2_phase3_agent-RhY0NR39nY
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:590183741681:runtime/sila2_phase3_agent-RhY0NR39nY
      agent_session_id: 1534a31d-7721-40c3-b955-8c11ab0dedaa
    codebuild:
      project_name: bedrock-agentcore-sila2_phase3_agent-builder
      execution_role: arn:aws:iam::590183741681:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-a64b67915b
      source_bucket: bedrock-agentcore-codebuild-sources-590183741681-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
