default_agent: sila2_agent
agents:
  sila2_agent:
    name: sila2_agent
    entrypoint: /local/home/tetsutm/dev/amazon-bedrock-agents-healthcare-lifesciences/agents_catalog/32-sila2-lab-automation-agent/main_agentcore.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /local/home/tetsutm/dev/amazon-bedrock-agents-healthcare-lifesciences/agents_catalog/32-sila2-lab-automation-agent
    aws:
      execution_role: arn:aws:iam::590183741681:role/sila2-main-stack-LambdaStack-1I-LambdaExecutionRole-HQnDUzZXTakQ
      execution_role_auto_create: true
      account: '590183741681'
      region: us-west-2
      ecr_repository: 590183741681.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-sila2_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: sila2_agent-ilKSgz3SI6
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:590183741681:runtime/sila2_agent-ilKSgz3SI6
      agent_session_id: de0f0e2c-5321-440d-9900-8dc5b983f0e8
    codebuild:
      project_name: bedrock-agentcore-sila2_agent-builder
      execution_role: arn:aws:iam::590183741681:role/sila2-main-stack-LambdaStack-1I-LambdaExecutionRole-HQnDUzZXTakQ
      source_bucket: bedrock-agentcore-codebuild-sources-590183741681-us-west-2
    memory:
      mode: STM_AND_LTM
      memory_id: sila2_memory-vNLitP6yIE
      memory_arn: arn:aws:bedrock-agentcore:us-west-2:590183741681:memory/sila2_memory-vNLitP6yIE
      memory_name: sila2_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
