[project]
name = "omop-data-harmonization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aws-cdk-lib>=2.212.0",
    "constructs>=10.4.2",
    "pandas>=2.3.2",
    "strands-agents==1.6.0",
]
