AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for AgentCore Resources"

Parameters:
  ProjectName:
    Type: String
    Description: "Name of the project for resource naming and tagging"
    Default: "research-agent"
    AllowedPattern: "^[a-zA-Z0-9-]+$"
    ConstraintDescription: "Must contain only alphanumeric characters and hyphens"
  S3CodeBucket:
    Description: Name of the S3 bucket to use for deployment and run storage
    Type: String
  S3CodeKey:
    Description: S3 key for the zip file containing CodeBuild code
    Type: String
  BuildContextPath:
    Description: Path to the build context directory
    Type: String
    Default: "."
  Timestamp:
    Description: Timestamp for the cfn deployment
    Type: Number
    Default: 9999999999
  WaitForCodeBuild:
    Description: Should CloudFormation wait for CodeBuild?
    Type: String
    Default: "N"
    AllowedValues: [Y, N]

Resources:
  ResearchEvidenceTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: "deep-research-evidence"
      AttributeDefinitions:
        - AttributeName: evidence_id
          AttributeType: S
        - AttributeName: source
          AttributeType: S
      KeySchema:
        - AttributeName: evidence_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: source_index
          KeySchema:
            - AttributeName: source
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  MultiAgentCoreRuntimeRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "Wildcard permissions required for AgentCore service operations and Bedrock model access"
          - id: W76
            reason: "High SPCM acceptable for AgentCore runtime role with broad service permissions"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock-agentcore.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
              ArnLike:
                aws:SourceArn: !Sub "arn:${AWS::Partition}:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:*"
      Policies:
        - PolicyName: StandardAgentCoreRuntimeExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ECRImageAccess
                Effect: Allow
                Action:
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
                Resource:
                  - !Sub "arn:${AWS::Partition}:ecr:${AWS::Region}:${AWS::AccountId}:repository/*"
              - Effect: Allow
                Action:
                  - logs:DescribeLogStreams
                  - logs:CreateLogGroup
                Resource:
                  - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/bedrock-agentcore/runtimes/*"
              - Effect: Allow
                Action:
                  - logs:DescribeLogGroups
                Resource:
                  - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:*"
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/bedrock-agentcore/runtimes/*:log-stream:*"
              - Sid: ECRTokenAccess
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: "*"
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                  - xray:GetSamplingRules
                  - xray:GetSamplingTargets
                Resource:
                  - "*"
              - Effect: Allow
                Resource: "*"
                Action: cloudwatch:PutMetricData
                Condition:
                  StringEquals:
                    cloudwatch:namespace: bedrock-agentcore
              - Sid: GetAgentAccessToken
                Effect: Allow
                Action:
                  - bedrock-agentcore:GetWorkloadAccessToken
                  - bedrock-agentcore:GetWorkloadAccessTokenForJWT
                  - bedrock-agentcore:GetWorkloadAccessTokenForUserId
                Resource:
                  - !Sub "arn:${AWS::Partition}:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:workload-identity-directory/default"
                  - !Sub "arn:${AWS::Partition}:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:workload-identity-directory/default/workload-identity/*"
              - Sid: BedrockModelInvocation
                Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource:
                  - !Sub "arn:${AWS::Partition}:bedrock:*::foundation-model/*"
                  - !Sub "arn:${AWS::Partition}:bedrock:${AWS::Region}:${AWS::AccountId}:*"
              - Sid: MarketplaceOperationsFromBedrockFor3pModels
                Effect: Allow
                Action:
                  - "aws-marketplace:Subscribe"
                  - "aws-marketplace:ViewSubscriptions"
                  - "aws-marketplace:Unsubscribe"
                Resource: "*"
                Condition:
                  StringEquals:
                    aws:CalledViaLast: "bedrock.amazonaws.com"
        - PolicyName: DynamoDb
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: DynamoDb
                Effect: Allow
                Action:
                  - dynamodb:CreateTable
                  - dynamodb:DescribeTable
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource:
                  - !GetAtt ResearchEvidenceTable.Arn
                  - !Sub "${ResearchEvidenceTable.Arn}/*"

  DRMultiContainer:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: "container.yaml"
      Parameters:
        S3CodeBucket: !Ref S3CodeBucket
        S3CodeKey: !Ref S3CodeKey
        BuildContextPath: !Sub "${BuildContextPath}/dr-multi-agent"
        Timestamp: !Ref Timestamp
        WaitForCodeBuild: !Ref WaitForCodeBuild
        BuildEnvironmentType: "ARM_CONTAINER"
        BuildComputeType: "BUILD_GENERAL1_SMALL"
        BuildImage: "aws/codebuild/amazonlinux2-aarch64-standard:3.0"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: Container

  DRMultiAgentRuntime:
    Type: AWS::BedrockAgentCore::Runtime
    Properties:
      AgentRuntimeArtifact:
        ContainerConfiguration:
          ContainerUri: !GetAtt DRMultiContainer.Outputs.ContainerURI
      AgentRuntimeName: "dr_multi_agent"
      Description: "Deep research multi agent with PMC access"
      NetworkConfiguration:
        NetworkMode: "PUBLIC"
      ProtocolConfiguration: "HTTP"
      RoleArn: !GetAtt MultiAgentCoreRuntimeRole.Arn
      Tags:
        Project: !Ref ProjectName
        Component: KBAgentRuntime
        Timestamp: !Ref Timestamp

Outputs:
  AgentCoreRuntimeRoleARN:
    Description: "AgentCore Runtime role ARN"
    Value: !GetAtt MultiAgentCoreRuntimeRole.Arn
  DRMultiContainerURI:
    Description: "Deep research agent container URI"
    Value: !GetAtt DRMultiContainer.Outputs.ContainerURI
  DRMultiAgentRuntimeID:
    Description: "Deep Research agent runtime ID"
    Value: !GetAtt DRMultiAgentRuntime.AgentRuntimeId
  DRMultiAgentRuntimeARN:
    Description: "Deep Research agent runtime ARN"
    Value: !GetAtt DRMultiAgentRuntime.AgentRuntimeArn
