AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for AgentCore Resources"

Parameters:
  ProjectName:
    Type: String
    Description: "Name of the project for resource naming and tagging"
    Default: "research-agent"
    AllowedPattern: "^[a-zA-Z0-9-]+$"
    ConstraintDescription: "Must contain only alphanumeric characters and hyphens"
  S3CodeBucket:
    Description: Name of the S3 bucket to use for deployment and run storage
    Type: String
  S3CodeKey:
    Description: S3 key for the zip file containing CodeBuild code
    Type: String
  BuildContextPath:
    Description: Path to the build context directory
    Type: String
    Default: "."
  Timestamp:
    Description: Timestamp for the cfn deployment
    Type: Number
    Default: 9999999999
  WaitForCodeBuild:
    Description: Should CloudFormation wait for CodeBuild?
    Type: String
    Default: "N"
    AllowedValues: [Y, N]

Resources:
  DRAgent:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: "dr-agent.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        S3CodeBucket: !Ref S3CodeBucket
        S3CodeKey: !Ref S3CodeKey
        BuildContextPath: !Ref BuildContextPath
        Timestamp: !Ref Timestamp
        WaitForCodeBuild: !Ref WaitForCodeBuild
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: Agent

  DRMultiAgent:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: "dr-multi-agent.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        S3CodeBucket: !Ref S3CodeBucket
        S3CodeKey: !Ref S3CodeKey
        BuildContextPath: !Ref BuildContextPath
        Timestamp: !Ref Timestamp
        WaitForCodeBuild: !Ref WaitForCodeBuild
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: Agent

Outputs:
  DRAgentID:
    Description: "Deep Research agent runtime ID"
    Value: !GetAtt DRAgent.Outputs.DRAgentRuntimeID
  DRMultiAgentID:
    Description: "Deep Research agent runtime ID"
    Value: !GetAtt DRMultiAgent.Outputs.DRMultiAgentRuntimeID
