# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import sila2_basic_pb2 as proto_dot_sila2__basic__pb2


class SiLA2DeviceStub(object):
    """Basic SiLA2 Device Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDeviceInfo = channel.unary_unary(
                '/sila2.SiLA2Device/GetDeviceInfo',
                request_serializer=proto_dot_sila2__basic__pb2.DeviceInfoRequest.SerializeToString,
                response_deserializer=proto_dot_sila2__basic__pb2.DeviceInfoResponse.FromString,
                )
        self.ExecuteCommand = channel.unary_unary(
                '/sila2.SiLA2Device/ExecuteCommand',
                request_serializer=proto_dot_sila2__basic__pb2.CommandRequest.SerializeToString,
                response_deserializer=proto_dot_sila2__basic__pb2.CommandResponse.FromString,
                )
        self.ListDevices = channel.unary_unary(
                '/sila2.SiLA2Device/ListDevices',
                request_serializer=proto_dot_sila2__basic__pb2.ListDevicesRequest.SerializeToString,
                response_deserializer=proto_dot_sila2__basic__pb2.ListDevicesResponse.FromString,
                )


class SiLA2DeviceServicer(object):
    """Basic SiLA2 Device Service
    """

    def GetDeviceInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SiLA2DeviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDeviceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceInfo,
                    request_deserializer=proto_dot_sila2__basic__pb2.DeviceInfoRequest.FromString,
                    response_serializer=proto_dot_sila2__basic__pb2.DeviceInfoResponse.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=proto_dot_sila2__basic__pb2.CommandRequest.FromString,
                    response_serializer=proto_dot_sila2__basic__pb2.CommandResponse.SerializeToString,
            ),
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=proto_dot_sila2__basic__pb2.ListDevicesRequest.FromString,
                    response_serializer=proto_dot_sila2__basic__pb2.ListDevicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sila2.SiLA2Device', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SiLA2Device(object):
    """Basic SiLA2 Device Service
    """

    @staticmethod
    def GetDeviceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sila2.SiLA2Device/GetDeviceInfo',
            proto_dot_sila2__basic__pb2.DeviceInfoRequest.SerializeToString,
            proto_dot_sila2__basic__pb2.DeviceInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sila2.SiLA2Device/ExecuteCommand',
            proto_dot_sila2__basic__pb2.CommandRequest.SerializeToString,
            proto_dot_sila2__basic__pb2.CommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sila2.SiLA2Device/ListDevices',
            proto_dot_sila2__basic__pb2.ListDevicesRequest.SerializeToString,
            proto_dot_sila2__basic__pb2.ListDevicesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
