# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sila2_streaming_pb2 as sila2__streaming__pb2


class SiLA2DeviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeTemperature = channel.unary_stream(
                '/SiLA2Device/SubscribeTemperature',
                request_serializer=sila2__streaming__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=sila2__streaming__pb2.TemperatureUpdate.FromString,
                )
        self.SubscribeEvents = channel.unary_stream(
                '/SiLA2Device/SubscribeEvents',
                request_serializer=sila2__streaming__pb2.EventRequest.SerializeToString,
                response_deserializer=sila2__streaming__pb2.DeviceEvent.FromString,
                )


class SiLA2DeviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeTemperature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SiLA2DeviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeTemperature': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTemperature,
                    request_deserializer=sila2__streaming__pb2.SubscribeRequest.FromString,
                    response_serializer=sila2__streaming__pb2.TemperatureUpdate.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=sila2__streaming__pb2.EventRequest.FromString,
                    response_serializer=sila2__streaming__pb2.DeviceEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SiLA2Device', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SiLA2Device(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/SiLA2Device/SubscribeTemperature',
            sila2__streaming__pb2.SubscribeRequest.SerializeToString,
            sila2__streaming__pb2.TemperatureUpdate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/SiLA2Device/SubscribeEvents',
            sila2__streaming__pb2.EventRequest.SerializeToString,
            sila2__streaming__pb2.DeviceEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
