default_agent: researchappagent
agents:
  researchappagent:
    name: researchappagent
    entrypoint: agent/main.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::440744262022:role/researchappStackInfra-RuntimeAgentCoreRole-PK5ItB4joRRa
      execution_role_auto_create: true
      account: '440744262022'
      region: us-west-2
      ecr_repository: 440744262022.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-researchappagent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: researchappagent-iWYD3z4Teh
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:440744262022:runtime/researchappagent-iWYD3z4Teh
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-researchappagent-builder
      execution_role: arn:aws:iam::440744262022:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-9af9cc648f
      source_bucket: bedrock-agentcore-codebuild-sources-440744262022-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
