agent_name: sila2_runtime_phase3
agent_description: "SiLA2 Lab Automation Agent Phase 3 - Complete Implementation"
model_id: anthropic.claude-3-5-sonnet-20241022-v2:0
region: us-west-2
execution_role_arn: arn:aws:iam::590183741681:role/sila2-lab-automation-phase3-inf-LambdaExecutionRole-Jpox8sK4J411
ecr_repository: 590183741681.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-sila2_runtime_phase3

tools:
  - name: list_devices
    description: "List all available SiLA2 devices in the laboratory"
    parameters:
      type: object
      properties: {}
  
  - name: device_status
    description: "Get current status and capabilities of a specific device"
    parameters:
      type: object
      properties:
        device_id:
          type: string
          description: "Device identifier (e.g., HPLC-01, CENTRIFUGE-01)"
      required: ["device_id"]
  
  - name: device_command
    description: "Execute a command on a specific device"
    parameters:
      type: object
      properties:
        device_id:
          type: string
          description: "Device identifier"
        command:
          type: string
          description: "Command to execute on the device"
        parameters:
          type: object
          description: "Optional command parameters"
      required: ["device_id", "command"]

  - name: start_measurement
    description: "Start a measurement process on a device"
    parameters:
      type: object
      properties:
        device_id:
          type: string
          description: "Device identifier"
        measurement_type:
          type: string
          description: "Type of measurement to perform"
        duration:
          type: number
          description: "Measurement duration in seconds"
      required: ["device_id", "measurement_type"]

  - name: stop_measurement
    description: "Stop an ongoing measurement on a device"
    parameters:
      type: object
      properties:
        device_id:
          type: string
          description: "Device identifier"
      required: ["device_id"]

  - name: get_measurement_data
    description: "Retrieve measurement data from a device"
    parameters:
      type: object
      properties:
        device_id:
          type: string
          description: "Device identifier"
        data_format:
          type: string
          description: "Desired data format (json, csv, xml)"
          default: "json"
      required: ["device_id"]

environment_variables:
  API_GATEWAY_URL: https://22ou5pzhd5.execute-api.us-west-2.amazonaws.com/dev
  ENVIRONMENT: dev
  PHASE: "3"