# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sila2_basic.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sila2_basic.proto\x12\x05sila2\"&\n\x11\x44\x65viceInfoRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"\xd1\x01\n\x12\x44\x65viceInfoResponse\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x03 \x01(\t\x12=\n\nproperties\x18\x04 \x03(\x0b\x32).sila2.DeviceInfoResponse.PropertiesEntry\x12\x11\n\ttimestamp\x18\x05 \x01(\t\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa4\x01\n\x0e\x43ommandRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x39\n\nparameters\x18\x03 \x03(\x0b\x32%.sila2.CommandRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xce\x01\n\x0f\x43ommandResponse\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x32\n\x06result\x18\x05 \x03(\x0b\x32\".sila2.CommandResponse.ResultEntry\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x1a-\n\x0bResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x14\n\x12ListDevicesRequest\"[\n\x13ListDevicesResponse\x12\"\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x11.sila2.DeviceInfo\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"V\n\nDeviceInfo\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t2\xda\x01\n\x0bSiLA2Device\x12\x44\n\rGetDeviceInfo\x12\x18.sila2.DeviceInfoRequest\x1a\x19.sila2.DeviceInfoResponse\x12?\n\x0e\x45xecuteCommand\x12\x15.sila2.CommandRequest\x1a\x16.sila2.CommandResponse\x12\x44\n\x0bListDevices\x12\x19.sila2.ListDevicesRequest\x1a\x1a.sila2.ListDevicesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sila2_basic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEVICEINFORESPONSE_PROPERTIESENTRY']._options = None
  _globals['_DEVICEINFORESPONSE_PROPERTIESENTRY']._serialized_options = b'8\001'
  _globals['_COMMANDREQUEST_PARAMETERSENTRY']._options = None
  _globals['_COMMANDREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_COMMANDRESPONSE_RESULTENTRY']._options = None
  _globals['_COMMANDRESPONSE_RESULTENTRY']._serialized_options = b'8\001'
  _globals['_DEVICEINFOREQUEST']._serialized_start=28
  _globals['_DEVICEINFOREQUEST']._serialized_end=66
  _globals['_DEVICEINFORESPONSE']._serialized_start=69
  _globals['_DEVICEINFORESPONSE']._serialized_end=278
  _globals['_DEVICEINFORESPONSE_PROPERTIESENTRY']._serialized_start=229
  _globals['_DEVICEINFORESPONSE_PROPERTIESENTRY']._serialized_end=278
  _globals['_COMMANDREQUEST']._serialized_start=281
  _globals['_COMMANDREQUEST']._serialized_end=445
  _globals['_COMMANDREQUEST_PARAMETERSENTRY']._serialized_start=396
  _globals['_COMMANDREQUEST_PARAMETERSENTRY']._serialized_end=445
  _globals['_COMMANDRESPONSE']._serialized_start=448
  _globals['_COMMANDRESPONSE']._serialized_end=654
  _globals['_COMMANDRESPONSE_RESULTENTRY']._serialized_start=609
  _globals['_COMMANDRESPONSE_RESULTENTRY']._serialized_end=654
  _globals['_LISTDEVICESREQUEST']._serialized_start=656
  _globals['_LISTDEVICESREQUEST']._serialized_end=676
  _globals['_LISTDEVICESRESPONSE']._serialized_start=678
  _globals['_LISTDEVICESRESPONSE']._serialized_end=769
  _globals['_DEVICEINFO']._serialized_start=771
  _globals['_DEVICEINFO']._serialized_end=857
  _globals['_SILA2DEVICE']._serialized_start=860
  _globals['_SILA2DEVICE']._serialized_end=1078
# @@protoc_insertion_point(module_scope)
