AWSTemplateFormatVersion: '2010-09-09'
Description: 'SiLA2 Lab Automation Agent Infrastructure'

Parameters:
  AgentName:
    Type: String
    Default: sila2_lab_automation_agent
    Description: Name of the SiLA2 agent

Resources:
  # ECR Repository
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub 'bedrock-agentcore-${AgentName}'
      ImageScanningConfiguration:
        ScanOnPush: true

  # IAM Role for AgentCore Runtime
  AgentCoreRuntimeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock-agentcore.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BedrockModelAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource: 
                  - !Sub 'arn:aws:bedrock:*:${AWS::AccountId}:inference-profile/us.anthropic.claude-3-5-sonnet-20241022-v2:0'
                  - !Sub 'arn:aws:bedrock:*::foundation-model/anthropic.claude-3-5-sonnet-20241022-v2:0'
        - PolicyName: XRayAndCloudWatchAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
        - PolicyName: ECRAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
                Resource: '*'
        - PolicyName: MCPLambdaAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AgentName}-mcp-server'

  # IAM Role for MCP Lambda Function
  MCPLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: MCPLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'

  # MCP Server Lambda Function
  MCPServerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AgentName}-mcp-server'
      Description: 'MCP Server for SiLA2 Lab Automation Agent'
      Runtime: python3.10
      Handler: mcp_server.lambda_handler
      Role: !GetAtt MCPLambdaRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': 'MCP Server placeholder - will be updated during deployment'
              }
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          AGENT_NAME: !Ref AgentName
          LOG_LEVEL: INFO
      Tags:
        - Key: Application
          Value: SiLA2LabAutomation
        - Key: Phase
          Value: '1'

  # CloudWatch Log Group for MCP Server
  MCPServerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AgentName}-mcp-server'
      RetentionInDays: 14

  # SSM Parameters for configuration
  MCPServerArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/sila2-agent/${AgentName}/mcp/server_arn'
      Type: String
      Value: !GetAtt MCPServerFunction.Arn
      Description: 'MCP Server Lambda Function ARN'

Outputs:
  ECRRepositoryURI:
    Description: ECR Repository URI
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/bedrock-agentcore-${AgentName}'
  
  RuntimeRoleArn:
    Description: AgentCore Runtime Role ARN
    Value: !GetAtt AgentCoreRuntimeRole.Arn

  MCPServerArn:
    Description: MCP Server Lambda Function ARN
    Value: !GetAtt MCPServerFunction.Arn

  MCPServerName:
    Description: MCP Server Lambda Function Name
    Value: !Ref MCPServerFunction