AWSTemplateFormatVersion: '2010-09-09'
Description: 'SiLA2 Lab Automation Agent - Phase 3 Full with AgentCore (us-west-2)'

Parameters:
  Environment:
    Type: String
    Default: dev

Resources:
  # IAM Role for Lambda functions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BedrockAgentCoreAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                  - bedrock-agent:*
                  - bedrock-runtime:*
                Resource: '*'

  # AgentCore Runtime Role
  AgentCoreRuntimeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
                - bedrock.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: AgentCoreRuntimePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:*
                  - lambda:InvokeFunction
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  # Gateway Tools Lambda (Enhanced)
  GatewayToolsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'sila2-lab-automation-gateway-tools-${Environment}'
      Runtime: python3.10
      Handler: sila2_gateway_tools_simplified.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          MOCK_DEVICE_API_URL: !Sub 'https://${MockDeviceApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
          PROTOCOL_BRIDGE_URL: !Sub 'https://${MockDeviceApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/bridge'
          GRPC_ENDPOINT: 'localhost:50051'
          ENVIRONMENT: !Ref Environment
      Code:
        ZipFile: |
          import json
          import os
          def lambda_handler(event, context):
              return {
                  'statusCode': 200, 
                  'body': json.dumps({
                      'message': 'SiLA2 Gateway Tools',
                      'api_url': os.environ.get('MOCK_DEVICE_API_URL'),
                      'environment': os.environ.get('ENVIRONMENT')
                  })
              }
      Timeout: 30
      MemorySize: 512

  # Protocol Bridge Lambda (Enhanced)
  ProtocolBridgeLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'sila2-protocol-bridge-${Environment}'
      Runtime: python3.10
      Handler: protocol_bridge_lambda_grpc.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          MOCK_DEVICE_API_URL: !Sub 'https://${MockDeviceApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
          GRPC_ENDPOINT: 'localhost:50051'
          ENVIRONMENT: !Ref Environment
      Code:
        ZipFile: |
          import json
          import os
          def lambda_handler(event, context):
              return {
                  'statusCode': 200, 
                  'body': json.dumps({
                      'message': 'SiLA2 Protocol Bridge with gRPC',
                      'grpc_endpoint': os.environ.get('GRPC_ENDPOINT'),
                      'environment': os.environ.get('ENVIRONMENT')
                  })
              }
      Timeout: 30
      MemorySize: 512

  # Mock Device Lambda (Enhanced)
  MockDeviceLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'sila2-mock-device-lambda-${Environment}'
      Runtime: python3.10
      Handler: mock_device_lambda_enhanced.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      Code:
        ZipFile: |
          import json
          import os
          def lambda_handler(event, context):
              return {
                  'statusCode': 200, 
                  'body': json.dumps({
                      'message': 'Enhanced Mock SiLA2 Device',
                      'environment': os.environ.get('ENVIRONMENT')
                  })
              }
      Timeout: 30
      MemorySize: 512

  # gRPC Device Lambda (Enhanced)
  GRPCDeviceLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'sila2-grpc-device-lambda-${Environment}'
      Runtime: python3.10
      Handler: lambda_grpc_device_handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      Code:
        ZipFile: |
          import json
          import os
          def lambda_handler(event, context):
              return {
                  'statusCode': 200, 
                  'body': json.dumps({
                      'message': 'gRPC Device Lambda Handler',
                      'environment': os.environ.get('ENVIRONMENT')
                  })
              }
      Timeout: 30
      MemorySize: 512

  # AgentCore Runtime Lambda (NEW)
  AgentCoreRuntimeLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'sila2-agentcore-runtime-${Environment}'
      Runtime: python3.10
      Handler: agentcore_runtime.lambda_handler
      Role: !GetAtt AgentCoreRuntimeRole.Arn
      Environment:
        Variables:
          GATEWAY_TOOLS_ARN: !GetAtt GatewayToolsLambda.Arn
          PROTOCOL_BRIDGE_ARN: !GetAtt ProtocolBridgeLambda.Arn
          ENVIRONMENT: !Ref Environment
      Code:
        ZipFile: |
          import json
          import os
          def lambda_handler(event, context):
              return {
                  'statusCode': 200, 
                  'body': json.dumps({
                      'message': 'AgentCore Runtime for SiLA2',
                      'gateway_tools': os.environ.get('GATEWAY_TOOLS_ARN'),
                      'protocol_bridge': os.environ.get('PROTOCOL_BRIDGE_ARN'),
                      'environment': os.environ.get('ENVIRONMENT')
                  })
              }
      Timeout: 60
      MemorySize: 1024

  # API Gateway for Mock Devices
  MockDeviceApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 'sila2-mock-device-api-${Environment}'
      Description: 'API Gateway for SiLA2 Mock Devices with AgentCore'

  # Devices Resource
  DevicesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MockDeviceApi
      ParentId: !GetAtt MockDeviceApi.RootResourceId
      PathPart: devices

  # Device Resource (with ID)
  DeviceResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MockDeviceApi
      ParentId: !GetAtt MockDeviceApi.RootResourceId
      PathPart: device

  # Device ID Resource
  DeviceIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MockDeviceApi
      ParentId: !Ref DeviceResource
      PathPart: '{device_id}'

  # Bridge Resource (NEW)
  BridgeResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MockDeviceApi
      ParentId: !GetAtt MockDeviceApi.RootResourceId
      PathPart: bridge

  # gRPC Resource
  GRPCResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MockDeviceApi
      ParentId: !GetAtt MockDeviceApi.RootResourceId
      PathPart: grpc

  # gRPC Devices Resource
  GRPCDevicesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MockDeviceApi
      ParentId: !Ref GRPCResource
      PathPart: devices

  # gRPC Device Resource
  GRPCDeviceResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MockDeviceApi
      ParentId: !Ref GRPCResource
      PathPart: device

  # gRPC Device ID Resource
  GRPCDeviceIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MockDeviceApi
      ParentId: !Ref GRPCDeviceResource
      PathPart: '{device_id}'

  # AgentCore Resource (NEW)
  AgentCoreResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MockDeviceApi
      ParentId: !GetAtt MockDeviceApi.RootResourceId
      PathPart: agentcore

  # Devices GET Method
  DevicesGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MockDeviceApi
      ResourceId: !Ref DevicesResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MockDeviceLambda.Arn}/invocations'

  # Device Status GET Method
  DeviceStatusGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MockDeviceApi
      ResourceId: !Ref DeviceIdResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MockDeviceLambda.Arn}/invocations'

  # Device Operation POST Method
  DeviceOperationPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MockDeviceApi
      ResourceId: !Ref DeviceIdResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MockDeviceLambda.Arn}/invocations'

  # Bridge GET Method (NEW)
  BridgeGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MockDeviceApi
      ResourceId: !Ref BridgeResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProtocolBridgeLambda.Arn}/invocations'

  # Bridge POST Method (NEW)
  BridgePostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MockDeviceApi
      ResourceId: !Ref BridgeResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProtocolBridgeLambda.Arn}/invocations'

  # gRPC Devices GET Method
  GRPCDevicesGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MockDeviceApi
      ResourceId: !Ref GRPCDevicesResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GRPCDeviceLambda.Arn}/invocations'

  # gRPC Device Status GET Method
  GRPCDeviceStatusGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MockDeviceApi
      ResourceId: !Ref GRPCDeviceIdResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GRPCDeviceLambda.Arn}/invocations'

  # gRPC Device Operation POST Method
  GRPCDeviceOperationPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MockDeviceApi
      ResourceId: !Ref GRPCDeviceIdResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GRPCDeviceLambda.Arn}/invocations'

  # AgentCore GET Method (NEW)
  AgentCoreGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MockDeviceApi
      ResourceId: !Ref AgentCoreResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AgentCoreRuntimeLambda.Arn}/invocations'

  # AgentCore POST Method (NEW)
  AgentCorePostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MockDeviceApi
      ResourceId: !Ref AgentCoreResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AgentCoreRuntimeLambda.Arn}/invocations'

  # Lambda Permissions
  MockDeviceLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MockDeviceLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MockDeviceApi}/*/*'

  ProtocolBridgeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProtocolBridgeLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MockDeviceApi}/*/*'

  GRPCDeviceLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GRPCDeviceLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MockDeviceApi}/*/*'

  AgentCoreRuntimeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AgentCoreRuntimeLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MockDeviceApi}/*/*'

  # API Gateway Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
      - DevicesGetMethod
      - DeviceStatusGetMethod
      - DeviceOperationPostMethod
      - BridgeGetMethod
      - BridgePostMethod
      - GRPCDevicesGetMethod
      - GRPCDeviceStatusGetMethod
      - GRPCDeviceOperationPostMethod
      - AgentCoreGetMethod
      - AgentCorePostMethod
    Properties:
      RestApiId: !Ref MockDeviceApi
      StageName: !Ref Environment

Outputs:
  GatewayToolsLambdaArn:
    Description: 'Gateway Tools Lambda ARN'
    Value: !GetAtt GatewayToolsLambda.Arn

  ProtocolBridgeLambdaArn:
    Description: 'Protocol Bridge Lambda ARN'
    Value: !GetAtt ProtocolBridgeLambda.Arn

  MockDeviceLambdaArn:
    Description: 'Mock Device Lambda ARN'
    Value: !GetAtt MockDeviceLambda.Arn

  GRPCDeviceLambdaArn:
    Description: 'gRPC Device Lambda ARN'
    Value: !GetAtt GRPCDeviceLambda.Arn

  AgentCoreRuntimeArn:
    Description: 'AgentCore Runtime Lambda ARN'
    Value: !GetAtt AgentCoreRuntimeLambda.Arn

  MockDeviceApiUrl:
    Description: 'Mock Device API Gateway URL'
    Value: !Sub 'https://${MockDeviceApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'

  ProtocolBridgeApiUrl:
    Description: 'Protocol Bridge API Gateway URL'
    Value: !Sub 'https://${MockDeviceApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/bridge'

  GRPCDeviceApiUrl:
    Description: 'gRPC Device API Gateway URL'
    Value: !Sub 'https://${MockDeviceApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/grpc'

  AgentCoreApiUrl:
    Description: 'AgentCore API Gateway URL'
    Value: !Sub 'https://${MockDeviceApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/agentcore'

  StackName:
    Description: 'CloudFormation Stack Name'
    Value: !Ref 'AWS::StackName'

  Region:
    Description: 'AWS Region'
    Value: !Ref 'AWS::Region'