AWSTemplateFormatVersion: '2010-09-09'
Description: 'EventBridge + SNS + Lambda for SiLA2 Agent'

Parameters:
  BridgeURL:
    Type: String
    Description: Bridge Server URL (e.g., http://bridge-container:8080)
  
  AgentCoreAgentId:
    Type: String
    Description: AgentCore Agent ID
  
  AgentCoreAliasId:
    Type: String
    Description: AgentCore Alias ID
  
  VpcId:
    Type: String
    Description: VPC ID for Lambda function
  
  PrivateSubnetIds:
    Type: CommaDelimitedList
    Description: Private Subnet IDs for Lambda function
  
  BridgeSecurityGroupId:
    Type: String
    Description: Security Group ID that allows access to Bridge Server

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: sila2-events-topic
      DisplayName: SiLA2 Device Events

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda function
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: BedrockAgentCoreInvoke
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock-agentcore:InvokeAgentRuntime
                  - bedrock-agentcore:InvokeAgent
                  - bedrock-agentcore:CreateEvent
                Resource: '*'

  InvokerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: sila2-agentcore-invoker
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 300
      Environment:
        Variables:
          BRIDGE_URL: http://bridge.sila2.local:8080
          AGENTCORE_AGENT_ID: !Ref AgentCoreAgentId
          AGENTCORE_ALIAS_ID: !Ref AgentCoreAliasId
          AGENTCORE_MEMORY_ID: ''
          AGENTCORE_RUNTIME_ARN: ''
          SNS_TOPIC_ARN: !Ref SNSTopic
      VpcConfig:
        SubnetIds: !Ref PrivateSubnetIds
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
          - !Ref BridgeSecurityGroupId
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {"statusCode": 200, "body": "Placeholder"}

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      TopicArn: !Ref SNSTopic
      Endpoint: !GetAtt InvokerFunction.Arn

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref InvokerFunction
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref SNSTopic

  EventBridgeRuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt InvokerFunction.Arn

  PeriodicCollectionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: sila2-periodic-data-collection
      Description: Periodic data collection from SiLA2 devices
      ScheduleExpression: rate(1 minute)
      State: ENABLED
      Targets:
        - Arn: !GetAtt InvokerFunction.Arn
          Id: PeriodicCollectionTarget
          Input: !Sub |
            {
              "action": "periodic",
              "devices": ["hplc_001", "hplc_002"]
            }

  EventBridgeInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref InvokerFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt PeriodicCollectionRule.Arn

Outputs:
  SNSTopicArn:
    Description: SNS Topic ARN for Bridge Server
    Value: !Ref SNSTopic
    Export:
      Name: SiLA2-SNS-Topic-ARN
  
  LambdaFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt InvokerFunction.Arn
  
  EventBridgeRuleName:
    Description: EventBridge Rule Name
    Value: !Ref PeriodicCollectionRule
