AWSTemplateFormatVersion: '2010-09-09'
Description: 'SiLA2 Lab Automation Agent - Main Stack'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for deployment
  
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Private Subnet IDs (minimum 2)
  
  RouteTableIds:
    Type: CommaDelimitedList
    Description: Route Table IDs for S3 Gateway Endpoint
  
  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
  
  DeploymentBucket:
    Type: String
    Description: S3 bucket for nested templates and Lambda code
  
  AgentCoreAgentId:
    Type: String
    Default: ''
    Description: AgentCore Agent ID (optional, can be set later)
  
  AgentCoreAliasId:
    Type: String
    Default: ''
    Description: AgentCore Alias ID (optional, can be set later)

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${DeploymentBucket}.s3.${AWS::Region}.amazonaws.com/nested/network.yaml
      Parameters:
        VpcId: !Ref VpcId
        SubnetIds: !Join [',', !Ref PrivateSubnetIds]
        RouteTableIds: !Join [',', !Ref RouteTableIds]
      TimeoutInMinutes: 15

  ECSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: !Sub https://${DeploymentBucket}.s3.${AWS::Region}.amazonaws.com/nested/ecs.yaml
      Parameters:
        VpcId: !Ref VpcId
        SubnetIds: !Join [',', !Ref PrivateSubnetIds]
        EnvironmentName: !Ref EnvironmentName
      TimeoutInMinutes: 30

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ECSStack
    Properties:
      TemplateURL: !Sub https://${DeploymentBucket}.s3.${AWS::Region}.amazonaws.com/nested/lambda.yaml
      Parameters:
        VpcId: !Ref VpcId
        PrivateSubnetIds: !Join [',', !Ref PrivateSubnetIds]
        BridgeSecurityGroup: !GetAtt ECSStack.Outputs.BridgeSecurityGroup
        DeploymentBucket: !Ref DeploymentBucket
        AgentCoreAgentId: !Ref AgentCoreAgentId
        AgentCoreAliasId: !Ref AgentCoreAliasId
      TimeoutInMinutes: 15

  EventsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdaStack
    Properties:
      TemplateURL: !Sub https://${DeploymentBucket}.s3.${AWS::Region}.amazonaws.com/nested/events.yaml
      Parameters:
        InvokerFunctionArn: !GetAtt LambdaStack.Outputs.InvokerFunctionArn
      TimeoutInMinutes: 10



Outputs:
  ClusterName:
    Description: ECS Cluster Name
    Value: !GetAtt ECSStack.Outputs.ClusterName
  
  BridgeEndpoint:
    Description: Bridge Server Endpoint (Service Discovery)
    Value: !GetAtt ECSStack.Outputs.BridgeServiceEndpoint
  
  ProxyFunctionArn:
    Description: Lambda Proxy Function ARN
    Value: !GetAtt LambdaStack.Outputs.ProxyFunctionArn
  
  InvokerFunctionArn:
    Description: Lambda Invoker Function ARN
    Value: !GetAtt LambdaStack.Outputs.InvokerFunctionArn
  
  SNSTopicArn:
    Description: SNS Topic ARN for Events
    Value: !GetAtt EventsStack.Outputs.SNSTopicArn
  
  BridgeSecurityGroup:
    Description: Bridge Security Group ID
    Value: !GetAtt ECSStack.Outputs.BridgeSecurityGroup
  
  VpcEndpointId:
    Description: VPC Endpoint ID for Bedrock AgentCore
    Value: !GetAtt NetworkStack.Outputs.VpcEndpointId
  
  LambdaRoleArn:
    Description: Lambda Execution Role ARN
    Value: !GetAtt LambdaStack.Outputs.LambdaRoleArn
  
  AnalyzeHeatingRateFunctionArn:
    Description: Analyze Heating Rate Lambda ARN
    Value: !GetAtt LambdaStack.Outputs.AnalyzeHeatingRateFunctionArn
