# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sila2_streaming.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15sila2_streaming.proto\"%\n\x10SubscribeRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"!\n\x0c\x45ventRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"\xae\x01\n\x11TemperatureUpdate\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x01\x12\x1a\n\x12target_temperature\x18\x03 \x01(\x01\x12\x17\n\x0f\x65lapsed_seconds\x18\x04 \x01(\x03\x12\x12\n\nstart_time\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x12\x15\n\rscenario_mode\x18\x07 \x01(\t\"\xbe\x01\n\x0b\x44\x65viceEvent\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\x12\x1a\n\x12target_temperature\x18\x04 \x01(\x01\x12\x18\n\x10\x64uration_seconds\x18\x05 \x01(\x03\x12\x15\n\rexpected_rate\x18\x06 \x01(\x01\x12\x13\n\x0b\x61\x63tual_rate\x18\x07 \x01(\x01\x12\x11\n\ttimestamp\x18\x08 \x01(\t2\x80\x01\n\x0bSiLA2Device\x12?\n\x14SubscribeTemperature\x12\x11.SubscribeRequest\x1a\x12.TemperatureUpdate0\x01\x12\x30\n\x0fSubscribeEvents\x12\r.EventRequest\x1a\x0c.DeviceEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sila2_streaming_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUBSCRIBEREQUEST']._serialized_start=25
  _globals['_SUBSCRIBEREQUEST']._serialized_end=62
  _globals['_EVENTREQUEST']._serialized_start=64
  _globals['_EVENTREQUEST']._serialized_end=97
  _globals['_TEMPERATUREUPDATE']._serialized_start=100
  _globals['_TEMPERATUREUPDATE']._serialized_end=274
  _globals['_DEVICEEVENT']._serialized_start=277
  _globals['_DEVICEEVENT']._serialized_end=467
  _globals['_SILA2DEVICE']._serialized_start=470
  _globals['_SILA2DEVICE']._serialized_end=598
# @@protoc_insertion_point(module_scope)
