openapi: 3.0.0
info:
  title: Wiley API
  version: 1.0.0
  description: API to get articles from an Open Access subset of Wiley Online Library related to Health Sciences
paths:
  /get-articles-from-wiley:
    get:
      summary: Gets scientific articles from an Open Access subset of Wiley Online Library related to Health Sciences
      description: This endpoint retrieves from an Open Access subset of Wiley Online Library related to Health Sciences based on a human query.
      operationId: getArticlesFromWiley
      parameters:
        - name: question
          in: query
          required: true
          description: The query string (human question) specifying the topic or information the user is seeking.
          schema:
            type: string
      responses:
        '200':
          description: Gets scientific articles from an Open Access subset of Wiley Online Library related to Health Sciences
          content:
            'application/json':
              schema:
                type: object
                properties:
                  text:
                    type: string
                    description: A list of citations and extracted text from the articles
                  wol_link:
                    type: string
                    description: The link to the Wiley Online Library page containing the article
