# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sila2_tasks.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sila2_tasks.proto\x12\x05sila2\"\xa6\x01\n\x10StartTaskRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12;\n\nparameters\x18\x03 \x03(\x0b\x32\'.sila2.StartTaskRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"/\n\x0cTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"$\n\x11TaskStatusRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"X\n\x12TaskStatusResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t2\x8e\x01\n\x0bTaskService\x12\x39\n\tStartTask\x12\x17.sila2.StartTaskRequest\x1a\x13.sila2.TaskResponse\x12\x44\n\rGetTaskStatus\x12\x18.sila2.TaskStatusRequest\x1a\x19.sila2.TaskStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sila2_tasks_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STARTTASKREQUEST_PARAMETERSENTRY']._options = None
  _globals['_STARTTASKREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_STARTTASKREQUEST']._serialized_start=29
  _globals['_STARTTASKREQUEST']._serialized_end=195
  _globals['_STARTTASKREQUEST_PARAMETERSENTRY']._serialized_start=146
  _globals['_STARTTASKREQUEST_PARAMETERSENTRY']._serialized_end=195
  _globals['_TASKRESPONSE']._serialized_start=197
  _globals['_TASKRESPONSE']._serialized_end=244
  _globals['_TASKSTATUSREQUEST']._serialized_start=246
  _globals['_TASKSTATUSREQUEST']._serialized_end=282
  _globals['_TASKSTATUSRESPONSE']._serialized_start=284
  _globals['_TASKSTATUSRESPONSE']._serialized_end=372
  _globals['_TASKSERVICE']._serialized_start=375
  _globals['_TASKSERVICE']._serialized_end=517
# @@protoc_insertion_point(module_scope)
